### ISSUE TITLE
variables to run 

### ISSUE THREAD

**Issue by benjyz** [DefiLlama/defillama-server#21]
trying to run server and missing some env variables. would this work with infura?

```
 Cannot resolve variable at "provider.environment.ETHEREUM_RPC": Value not found at "file" source,
  - Cannot resolve variable at "provider.environment.BSC_RPC": Value not found at "file" source,
  - Cannot resolve variable at "provider.environment.POLYGON_RPC": Value not found at "file" source,
  - Cannot resolve variable at "provider.environment.OUTDATED_WEBHOOK": Value not found at "file" source
```

**Comment by 0xngmi** [comment]
You'll need to create a `.env` file with the variables listed there, for the RPC you can copy them from [here](https://github.com/DefiLlama/defillama-sdk/blob/master/src/general.ts#L3), and you can set anything for `OUTDATED_WEBHOOK`, since it's only used to send a periodic discord server, and as long as that periodic lambda function is not triggered nothing will happen.

**Comment by 0xngmi** [comment]
You might also need to deploy multiple things, such as a dynamodb database

**Comment by 0xngmi** [comment]
Should we close this?
