### ISSUE TITLE
Add utility to compute old tvl.

### ISSUE THREAD

**Issue by fabioDMFerreira** [DefiLlama/defillama-server#5]
Start point: `src/cli/recomputeDaily.ts`

The function `storeTvl` in `src/storeTvlInterval/getAndStoreTvl.ts` already accepts the block and the timestamp associated with the block. The utility job should be to find the desired blocks and execute the `storeTvl` to store the old tvls.

**Comment by 0xngmi** [comment]
Implemented on src/cli/fillOld.ts

**Comment by fabioDMFerreira** [comment]
I've looked into it and it seems to support only one project per execution. Currently, it is set to "Stacks".

I'm thinking if it makes sense to use the start date property in the adapters to define the initial date we need to get the locked values.

**Comment by 0xngmi** [comment]
Yeah, the plan is to change it manually, although I'll need to make some extra changes since right now it's way too slow. Lots of ways it can be improved as well.

> I'm thinking if it makes sense to use the start date property in the adapters to define the initial date we need to get the locked values.
Good idea, I didn't use it because in some of the adapters I've created I've just left it empty but we can still use that data when we have it.

**Comment by 0xngmi** [comment]
Closing since this has been implemented already
